baseURL = 'https://xoloscript.github.io/'
languageCode = 'en-us'
title = 'XOLOS'
theme = "nightfall"

[params]
author = "xolos"
user = "xolos"
hostname = "script"
footerHtml = '<a href="https://github.com/xoloscript" class"footerLink">xoloscript</a> 2023 '
published = false
readingTime = false


[[params.social]]
key = 0
name = "github"
url = "https://github.com/xoloscript"
icon = "fa-brands fa-github"

[menu]
	[[menu.header]]
		name = "posts"
		weight = 0
		url = "/posts"


